#!/usr/bin/env python3
"""
maintenance.py — 隔週 Tableau Cloud 管理メンテナンス

実行:
    python maintenance.py

出力: reports/maintenance_YYYY-MM-DD.md
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from tableau_client import fetch_all


# ── ヘルパー ──────────────────────────────────────────────────────────────────

def _days_ago(iso: str | None) -> int:
    if not iso:
        return 9999
    try:
        dt = datetime.fromisoformat(iso)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return (datetime.now(timezone.utc) - dt).days
    except Exception:
        return 9999


def _date(iso: str | None) -> str:
    if not iso:
        return "—"
    return iso[:10]


# ── メイン ────────────────────────────────────────────────────────────────────

def run_maintenance() -> str:
    print("📋 Tableau Cloud メンテナンスチェック開始...")

    data  = fetch_all()
    wbs   = data["workbooks"]
    dss   = data["datasources"]
    users = data["users"]
    flows = data["flows"]

    now   = datetime.now(timezone.utc)
    today = now.strftime("%Y-%m-%d")

    # ── チェック項目 ──
    stale_wbs       = [w for w in wbs   if _days_ago(w.get("updated_at")) >= 180]
    stale_dss       = [d for d in dss   if _days_ago(d.get("updated_at")) >= 180]
    inactive_users  = [u for u in users if _days_ago(u.get("last_login"))  >= 90]
    uncert_dss      = [d for d in dss   if not d.get("certified")]
    ktw_wbs         = [w for w in wbs   if "KTW" in (w.get("tags") or [])]

    # ── レポート構築 ──
    L: list[str] = []

    def h(text: str) -> None:
        L.extend(["", f"## {text}", ""])

    L += [
        f"# Tableau Cloud メンテナンスレポート",
        f"**実行日:** {today}",
        "",
        "---",
        "",
        "## サマリ",
        "",
        "| 項目 | 件数 |",
        "|---|---|",
        f"| ワークブック総数 | {len(wbs)} |",
        f"| データソース総数 | {len(dss)} |",
        f"| フロー総数 | {len(flows)} |",
        f"| ユーザー総数 | {len(users)} |",
        f"| 180日以上未更新 WB | **{len(stale_wbs)}** |",
        f"| 180日以上未更新 DS | **{len(stale_dss)}** |",
        f"| 90日以上未ログインユーザー | **{len(inactive_users)}** |",
        f"| 未認定データソース | {len(uncert_dss)} |",
        f"| KTW監視対象 WB | {len(ktw_wbs)} |",
        "",
        "---",
    ]

    # ── 180日以上未更新 WB ──
    if stale_wbs:
        h("⚠️ 180日以上未更新ワークブック（削除/アーカイブ検討）")
        L += [
            "| ワークブック | プロジェクト | オーナー | 最終更新 | 経過日数 |",
            "|---|---|---|---|---|",
        ]
        for w in sorted(stale_wbs, key=lambda x: _days_ago(x.get("updated_at")), reverse=True):
            L.append(
                f"| {w['name']} | {w.get('project','—')} | {w.get('owner','—')} "
                f"| {_date(w.get('updated_at'))} | {_days_ago(w.get('updated_at'))}日 |"
            )

    # ── 90日以上未ログインユーザー ──
    if inactive_users:
        h("⚠️ 90日以上未ログインユーザー（ライセンス見直し検討）")
        L += [
            "| ユーザー | メール | ライセンス | 最終ログイン | 経過日数 |",
            "|---|---|---|---|---|",
        ]
        for u in sorted(inactive_users, key=lambda x: _days_ago(x.get("last_login")), reverse=True):
            last = _date(u.get("last_login")) if u.get("last_login") else "未ログイン"
            days = _days_ago(u.get("last_login"))
            days_str = "—" if days == 9999 else f"{days}日"
            L.append(
                f"| {u['name']} | {u.get('email','—')} | {u.get('site_role','—')} "
                f"| {last} | {days_str} |"
            )

    # ── KTW 監視 WB ──
    if ktw_wbs:
        h("🔍 KTW監視対象ワークブック")
        L += [
            "| ワークブック | プロジェクト | 最終更新 | タグ |",
            "|---|---|---|---|",
        ]
        for w in ktw_wbs:
            tags = ", ".join(w.get("tags") or [])
            L.append(
                f"| {w['name']} | {w.get('project','—')} "
                f"| {_date(w.get('updated_at'))} | {tags} |"
            )

    # ── 未認定 DS ──
    if uncert_dss:
        h("ℹ️ 未認定データソース")
        L += [
            "| データソース | プロジェクト | オーナー | 最終更新 |",
            "|---|---|---|---|",
        ]
        for d in uncert_dss:
            L.append(
                f"| {d['name']} | {d.get('project','—')} "
                f"| {d.get('owner','—')} | {_date(d.get('updated_at'))} |"
            )

    # ── 次回アクション ──
    L += [
        "",
        "---",
        "",
        "## 次回アクション",
        "",
        "- [ ] 未更新WBについてオーナーに確認・削除判断",
        "- [ ] 未ログインユーザーのライセンス見直し",
        "- [ ] KTW監視WBの差分タブで計算フィールド変更を確認",
        "- [ ] 未認定DSの認定可否を確認",
        "",
        "---",
        "",
        f"*Generated by Tableau Cloud Manager `maintenance.py`  "
        f"at {now.strftime('%Y-%m-%d %H:%M UTC')}*",
    ]

    report = "\n".join(L)

    # ── ファイル出力 ──
    out_dir = Path(__file__).parent / "reports"
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / f"maintenance_{today}.md"
    out_path.write_text(report, encoding="utf-8")

    print(f"✅ レポート生成: {out_path}")
    print(f"   未更新WB {len(stale_wbs)}件 / 未ログインUser {len(inactive_users)}件 / KTW {len(ktw_wbs)}件")

    return str(out_path)


if __name__ == "__main__":
    run_maintenance()
